(function () {
  const copy = {
    ko: {
      selectType: '회원 유형을 선택해주세요.',
      formInvalid: '필수 정보를 다시 확인해주세요.',
      confirmTerms: '필수 약관에 동의해야 가입할 수 있습니다.',
      processing: '가입을 처리하고 있습니다. 잠시만 기다려주세요...',
      duplicateChannel: '이미 등록된 채널 URL입니다. 다른 URL을 입력해주세요.',
      platformRequired: '주요 판매 플랫폼을 최소 1개 이상 선택해주세요.',
      signupSuccess: '가입이 완료되었습니다. 이메일 인증을 진행해주세요.',
      signupError: '가입 중 오류가 발생했습니다. 잠시 후 다시 시도해주세요.',
      noSupabase: '시스템 설정에 문제가 있습니다. 잠시 후 다시 시도해주세요.',
      help_supplier: '공급업체는 회사/브랜드명과 사업자등록번호를 필수로 입력해야 합니다.',
      help_seller: '셀러는 연락처와 운영 중인 채널 정보를 알려주세요. 회사명과 사업자등록번호는 필요하지 않습니다.',
      help_member: '일반회원은 기본 연락처만 입력하면 가입이 완료됩니다.',
      previewTitle: '신청 정보 미리보기',
      previewUserType: '회원 유형',
      previewName: '이름',
      previewEmail: '이메일',
      previewPhone: '연락처',
      previewCompany: '회사/브랜드',
      previewBusinessNumber: '사업자등록번호',
      previewPlatforms: '주요 플랫폼',
      previewChannel: '채널 URL',
      previewMarketing: '마케팅 수신',
      previewMarketingYes: '동의',
      previewMarketingNo: '미동의',
      userType_supplier: '공급업체',
      userType_seller: '셀러',
      userType_member: '일반회원'
    },
    en: {
      selectType: 'Please choose your membership type.',
      formInvalid: 'Please check the required information again.',
      confirmTerms: 'You must agree to the required terms to continue.',
      processing: 'Processing your registration. Please wait...',
      duplicateChannel: 'This channel URL is already registered. Please use a different one.',
      platformRequired: 'Select at least one primary platform.',
      signupSuccess: 'Registration complete. Please verify your email.',
      signupError: 'An error occurred while signing up. Please try again later.',
      noSupabase: 'Configuration error detected. Please try again soon.',
      help_supplier: 'Suppliers must provide a company/brand name and business registration number.',
      help_seller: 'Sellers only need to share contact and channel details—company information is not required.',
      help_member: 'Members can join with just their basic contact information.',
      previewTitle: 'Registration Preview',
      previewUserType: 'Member Type',
      previewName: 'Full Name',
      previewEmail: 'Email',
      previewPhone: 'Phone',
      previewCompany: 'Company/Brand',
      previewBusinessNumber: 'Business Registration',
      previewPlatforms: 'Primary Platforms',
      previewChannel: 'Channel URL',
      previewMarketing: 'Marketing Consent',
      previewMarketingYes: 'Consented',
      previewMarketingNo: 'Declined',
      userType_supplier: 'Supplier',
      userType_seller: 'Seller',
      userType_member: 'Member'
    },
    zh: {
      selectType: '请选择会员类型。',
      formInvalid: '请再次确认必填信息。',
      confirmTerms: '必须同意必需条款才能继续。',
      processing: '正在处理您的注册，请稍候……',
      duplicateChannel: '该频道 URL 已被注册，请输入其他地址。',
      platformRequired: '请至少选择一个主要销售平台。',
      signupSuccess: '注册完成。请前往邮箱完成验证。',
      signupError: '注册过程中发生错误，请稍后再试。',
      noSupabase: '系统配置出现问题，请稍后再试。',
      help_supplier: '供应商需填写公司/品牌名称及营业执照号码。',
      help_seller: '卖家只需提供联系方式和正在运营的频道信息，无需填写公司资料。',
      help_member: '普通会员仅需填写基本联系方式即可完成注册。',
      previewTitle: '注册信息预览',
      previewUserType: '会员类型',
      previewName: '姓名',
      previewEmail: '邮箱',
      previewPhone: '联系电话',
      previewCompany: '公司/品牌',
      previewBusinessNumber: '营业执照号码',
      previewPlatforms: '主要平台',
      previewChannel: '频道 URL',
      previewMarketing: '营销同意',
      previewMarketingYes: '同意',
      previewMarketingNo: '不同意',
      userType_supplier: '供应商',
      userType_seller: '卖家',
      userType_member: '普通会员'
    }
  };

  window.luceSignupCopy = copy;
})();
